package dev.franklindot04.learnjava.reliableservice;

import org.junit.jupiter.api.Test;import java.time.*;import java.util.concurrent.*;import static org.junit.jupiter.api.Assertions.*;

class ReliableCheckoutServiceTest {
  static final Clock CLOCK=Clock.fixed(Instant.parse("2026-01-01T00:00:00Z"), ZoneOffset.UTC);
  CheckoutRequest req(String key){return new CheckoutRequest(key,"fp-"+key,"sku",1,100);}
  @Test void healthyCheckoutSucceeds(){ var s=new ReliableCheckoutService(CLOCK,2,1,new FailurePlan(),new FailurePlan(),new FailurePlan()); var r=s.checkout(req("a"),Duration.ofSeconds(1)); assertEquals(CheckoutStatus.SUCCESS,r.status()); assertEquals(1,s.metrics().paymentCharges); }
  @Test void inventoryTransientRetries(){ var s=new ReliableCheckoutService(CLOCK,2,1,new FailurePlan(FailureType.TRANSIENT),new FailurePlan(),new FailurePlan()); var r=s.checkout(req("b"),Duration.ofSeconds(1)); assertEquals(CheckoutStatus.SUCCESS,r.status()); assertTrue(r.diagnostics().stream().anyMatch(x->x.contains("attempt 2"))); }
  @Test void paymentFatalStopsProcessing(){ var s=new ReliableCheckoutService(CLOCK,2,1,new FailurePlan(),new FailurePlan(FailureType.FATAL),new FailurePlan()); assertEquals(CheckoutStatus.FAILED,s.checkout(req("c"),Duration.ofSeconds(1)).status()); }
  @Test void notificationFailureDegrades(){ var s=new ReliableCheckoutService(CLOCK,2,1,new FailurePlan(),new FailurePlan(),new FailurePlan(FailureType.FATAL)); assertEquals(CheckoutStatus.DEGRADED,s.checkout(req("d"),Duration.ofSeconds(1)).status()); assertEquals(1,s.metrics().degraded); }
  @Test void repeatedInventoryFailuresOpenBreakerAndFailFast(){ var s=new ReliableCheckoutService(CLOCK,2,1,new FailurePlan(FailureType.FATAL,FailureType.FATAL),new FailurePlan(),new FailurePlan()); assertEquals(CheckoutStatus.FAILED,s.checkout(req("e"),Duration.ofSeconds(1)).status()); assertEquals(CheckoutStatus.FAILED,s.checkout(req("f"),Duration.ofSeconds(1)).status()); var r=s.checkout(req("g"),Duration.ofSeconds(1)); assertEquals(CheckoutStatus.FAILED,r.status()); assertTrue(r.message().contains("open")); }
  @Test void duplicateDoesNotRepeatSideEffectsAndChangedFingerprintRejected(){ var s=new ReliableCheckoutService(CLOCK,2,1,new FailurePlan(),new FailurePlan(),new FailurePlan()); assertEquals(CheckoutStatus.SUCCESS,s.checkout(req("h"),Duration.ofSeconds(1)).status()); assertEquals(CheckoutStatus.SUCCESS,s.checkout(req("h"),Duration.ofSeconds(1)).status()); assertEquals(1,s.metrics().paymentCharges); assertEquals(CheckoutStatus.FAILED,s.checkout(new CheckoutRequest("h","changed","sku",1,100),Duration.ofSeconds(1)).status()); }
  @Test void invalidExpiredAndJournal(){ var s=new ReliableCheckoutService(CLOCK,1,1,new FailurePlan(),new FailurePlan(),new FailurePlan()); assertEquals(CheckoutStatus.FAILED,s.checkout(new CheckoutRequest("i","fp","sku",0,100),Duration.ofSeconds(1)).status()); assertEquals(CheckoutStatus.REJECTED,s.checkout(req("j"),Duration.ZERO).status()); assertFalse(s.journal().events().isEmpty()); }
  @Test void saturatedBulkheadCanReject(){ var s=new ReliableCheckoutService(CLOCK,2,1,new FailurePlan(FailureType.TIMEOUT,FailureType.TIMEOUT,FailureType.TIMEOUT),new FailurePlan(),new FailurePlan()); assertEquals(CheckoutStatus.FAILED,s.checkout(req("k"),Duration.ofSeconds(1)).status()); assertTrue(s.journal().events().stream().anyMatch(e->e.contains("failed"))); }
}
