package dev.franklindot04.learnjava.reliableservice;

import java.time.*;import java.util.*;import java.util.concurrent.*;import java.util.concurrent.atomic.*;

public final class ReliableCheckoutService {
  private final Map<String, CheckoutResponse> idempotency=new ConcurrentHashMap<>(); private final Map<String,String> fingerprints=new ConcurrentHashMap<>();
  private final Semaphore load; private final Semaphore bulkhead; private final RecoveryJournal journal=new RecoveryJournal(); private final ReliabilityMetrics metrics=new ReliabilityMetrics();
  private final FailurePlan inventory; private final FailurePlan payment; private final FailurePlan notification; private final Clock clock; private Instant openedAt=Instant.MIN; private int inventoryFailures; private boolean open;
  public ReliableCheckoutService(Clock clock, int concurrency, int bulkheadPermits, FailurePlan inventory, FailurePlan payment, FailurePlan notification){ if(concurrency<1||bulkheadPermits<1) throw new IllegalArgumentException("limits must be positive"); this.clock=clock; this.load=new Semaphore(concurrency); this.bulkhead=new Semaphore(bulkheadPermits); this.inventory=inventory; this.payment=payment; this.notification=notification; }
  public CheckoutResponse checkout(CheckoutRequest request, Duration budget) { if(request.quantity()<1||request.cents()<1) return failed("invalid request"); RequestContext ctx=new RequestContext(clock, clock.instant().plus(budget)); if(ctx.expired()) return reject("deadline expired before work"); if(!load.tryAcquire()) return reject("service overloaded"); try { String old=fingerprints.putIfAbsent(request.idempotencyKey(), request.fingerprint()); if(old!=null&&!old.equals(request.fingerprint())) return failed("idempotency key reused with changed request"); return idempotency.computeIfAbsent(request.idempotencyKey(), key -> process(request, ctx)); } finally { load.release(); } }
  private CheckoutResponse process(CheckoutRequest request, RequestContext ctx){ List<String> d=new ArrayList<>(); metrics.accepted++; if(ctx.expired()) return reject("deadline expired"); try { reserveInventory(d); chargePayment(d); d.add("shipping quote selected"); try { notification.maybeFail(); d.add("notification sent"); } catch (PlannedFailure ex) { metrics.degraded++; journal.record("notification degraded"); d.add("notification fallback recorded"); return new CheckoutResponse(CheckoutStatus.DEGRADED,"checkout accepted; notification deferred",List.copyOf(d)); } journal.record("checkout success"); return new CheckoutResponse(CheckoutStatus.SUCCESS,"checkout completed",List.copyOf(d)); } catch (Exception ex) { journal.record("checkout failed: "+ex.getMessage()); return new CheckoutResponse(CheckoutStatus.FAILED,ex.getMessage(),List.copyOf(d)); } }
  private void reserveInventory(List<String> d) throws Exception { if(open && clock.instant().isBefore(openedAt.plusSeconds(5))) throw new IllegalStateException("inventory circuit breaker open"); if(!bulkhead.tryAcquire()) throw new RejectedExecutionException("inventory bulkhead saturated"); try { for(int attempt=1; attempt<=3; attempt++){ try{ inventory.maybeFail(); inventoryFailures=0; open=false; metrics.inventoryReservations++; d.add("inventory reserved on attempt "+attempt); return; } catch(PlannedFailure ex){ d.add("inventory "+ex.type+" on attempt "+attempt); if(!ex.retryable()||attempt==3){ inventoryFailures++; if(inventoryFailures>=2){open=true; openedAt=clock.instant(); journal.record("inventory breaker opened");} throw ex; } } } } finally { bulkhead.release(); } }
  private void chargePayment(List<String> d) throws PlannedFailure { payment.maybeFail(); metrics.paymentCharges++; d.add("payment charged"); }
  private CheckoutResponse reject(String m){metrics.rejected++; journal.record(m); return new CheckoutResponse(CheckoutStatus.REJECTED,m,List.of(m));}
  private CheckoutResponse failed(String m){journal.record(m); return new CheckoutResponse(CheckoutStatus.FAILED,m,List.of(m));}
  public RecoveryJournal journal(){return journal;} public ReliabilityMetrics metrics(){return metrics;}
}
