package dev.franklindot04.learnjava.reliability;

import org.junit.jupiter.api.Test;
import java.time.*;import java.util.*;import java.util.concurrent.*;import java.util.concurrent.atomic.*;
import static org.junit.jupiter.api.Assertions.*;

class ReliabilityPatternsTest {
  static final class MutableClock extends Clock { Instant now=Instant.parse("2026-01-01T00:00:00Z"); public ZoneId getZone(){return ZoneOffset.UTC;} public Clock withZone(ZoneId zone){return this;} public Instant instant(){return now;} void plus(Duration d){now=now.plus(d);} }
  static class TransientFailure extends Exception {} static class FatalFailure extends Exception {}
  @Test void retryScenarios() throws Exception { MutableClock c=new MutableClock(); List<Long> sleeps=new ArrayList<>(); RetryExecutor ex=new RetryExecutor(new RetryPolicy(3,Duration.ofMillis(10),Duration.ofMillis(25),Duration.ofSeconds(1)), Throwable.class::isInstance, new ExponentialBackoff(Duration.ofMillis(10),Duration.ofMillis(25), n->n+1), ms->{sleeps.add(ms); c.plus(Duration.ofMillis(ms));}, c); AtomicInteger calls=new AtomicInteger(); assertEquals("ok", ex.execute(()-> calls.incrementAndGet()==1?"ok":"bad")); AtomicInteger flaky=new AtomicInteger(); assertEquals("done", ex.execute(()->{ if(flaky.incrementAndGet()<2) throw new TransientFailure(); return "done";})); assertEquals(List.of(11L), sleeps); }
  @Test void nonRetryableAndExhaustedPreserveFailure() { MutableClock c=new MutableClock(); RetryExecutor ex=new RetryExecutor(new RetryPolicy(2,Duration.ofMillis(10),Duration.ofMillis(20),Duration.ofSeconds(1)), f->f instanceof TransientFailure, new ExponentialBackoff(Duration.ofMillis(10),Duration.ofMillis(20), n->n), ms->{}, c); assertThrows(FatalFailure.class, () -> ex.execute(()->{throw new FatalFailure();})); TransientFailure original=assertThrows(TransientFailure.class, () -> ex.execute(()->{throw new TransientFailure();})); assertNotNull(original); }
  @Test void backoffCapJitterBudgetAndInvalidConfig() { ExponentialBackoff b=new ExponentialBackoff(Duration.ofMillis(10),Duration.ofMillis(25), n->n-1); assertEquals(Duration.ofMillis(9), b.delayForAttempt(2)); assertEquals(Duration.ofMillis(24), b.delayForAttempt(5)); MutableClock c=new MutableClock(); RetryExecutor ex=new RetryExecutor(new RetryPolicy(3,Duration.ofMillis(10),Duration.ofMillis(20),Duration.ofMillis(5)), f->true, b, ms->{}, c); assertThrows(Exception.class, () -> ex.execute(()->{throw new TransientFailure();})); assertThrows(IllegalArgumentException.class, () -> new RetryPolicy(0,Duration.ofMillis(1),Duration.ofMillis(1),Duration.ofMillis(1))); }
  @Test void circuitBreakerTransitions() throws Exception { MutableClock c=new MutableClock(); CircuitBreaker cb=new CircuitBreaker(2,Duration.ofSeconds(5),c); assertThrows(TransientFailure.class, () -> cb.call(()->{throw new TransientFailure();})); assertThrows(TransientFailure.class, () -> cb.call(()->{throw new TransientFailure();})); assertEquals(CircuitBreakerState.OPEN, cb.snapshot().state()); assertThrows(IllegalStateException.class, () -> cb.call(()->"x")); c.plus(Duration.ofSeconds(5)); assertEquals(CircuitBreakerState.HALF_OPEN, cb.snapshot().state()); assertEquals("ok", cb.call(()->"ok")); assertEquals(CircuitBreakerState.CLOSED, cb.snapshot().state()); assertThrows(TransientFailure.class, () -> cb.call(()->{throw new TransientFailure();})); assertThrows(TransientFailure.class, () -> cb.call(()->{throw new TransientFailure();})); c.plus(Duration.ofSeconds(5)); assertThrows(TransientFailure.class, () -> cb.call(()->{throw new TransientFailure();})); assertEquals(CircuitBreakerState.OPEN, cb.snapshot().state()); }
  @Test void bulkheadReleasesPermits() throws Exception { Bulkhead b=new Bulkhead(1); CountDownLatch entered=new CountDownLatch(1); CountDownLatch release=new CountDownLatch(1); FutureTask<String> task=new FutureTask<>(()->b.execute(()->{entered.countDown(); release.await(); return "ok";})); Thread t=new Thread(task); t.start(); assertTrue(entered.await(1,TimeUnit.SECONDS)); assertThrows(BulkheadRejectedException.class, () -> b.execute(()->"no")); release.countDown(); assertEquals("ok", task.get(1,TimeUnit.SECONDS)); assertEquals(1,b.available()); assertThrows(RuntimeException.class, () -> b.execute(()->{throw new RuntimeException("boom");})); assertEquals(1,b.available()); }
  @Test void idempotencyAndLoadShedding() throws Exception { InMemoryIdempotencyStore<String> store=new InMemoryIdempotencyStore<>(); AtomicInteger side=new AtomicInteger(); assertEquals("one", store.executeOnce("k","fp",()->{side.incrementAndGet(); return "one";})); assertEquals("one", store.executeOnce("k","fp",()->"two")); assertEquals(1,side.get()); assertThrows(IllegalArgumentException.class, () -> store.executeOnce("k","changed",()->"x")); InMemoryIdempotencyStore<Integer> concurrent=new InMemoryIdempotencyStore<>(); AtomicInteger count=new AtomicInteger(); ExecutorService pool=Executors.newFixedThreadPool(2); try { Future<Integer> a=pool.submit(()->concurrent.executeOnce("a","same",()->{Thread.sleep(30); return count.incrementAndGet();})); Future<Integer> b=pool.submit(()->concurrent.executeOnce("a","same",()->count.incrementAndGet())); assertEquals(1,a.get()); assertEquals(1,b.get()); assertEquals(1,count.get()); } finally { pool.shutdownNow(); } MutableClock c=new MutableClock(); LoadShedder shedder=new LoadShedder(1); CountDownLatch entered=new CountDownLatch(1); CountDownLatch release=new CountDownLatch(1); FutureTask<String> inFlight=new FutureTask<>(()->shedder.execute(new RequestBudget(c,Duration.ofSeconds(1)),()->{entered.countDown(); release.await(); return "ok";})); Thread t=new Thread(inFlight); t.start(); assertTrue(entered.await(1,TimeUnit.SECONDS)); assertThrows(RejectedExecutionException.class, () -> shedder.execute(new RequestBudget(c,Duration.ofSeconds(1)),()->"no")); MutableClock expired=new MutableClock(); RequestBudget budget=new RequestBudget(expired,Duration.ofMillis(1)); expired.plus(Duration.ofMillis(1)); assertThrows(RejectedExecutionException.class, () -> shedder.execute(budget,()->"late")); release.countDown(); assertEquals("ok", inFlight.get(1,TimeUnit.SECONDS)); assertEquals(1,shedder.accepted()); assertEquals(2,shedder.rejected()); }
}
